name: Free RDP on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360  # Max 6 hours allowed

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .

    - name: Setup Ngrok Authtoken
      run: .\ngrok.exe authtoken YOUR_NGROK_AUTH_TOKEN

    - name: Start RDP Tunnel
      run: .\ngrok.exe tcp 3389

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Show IP and Port
      run: |
        curl http://127.0.0.1:4040/api/tunnels
